# Development overrides
# This file is automatically loaded in development
version: '3.8'

services:
  hafiportrait-dev:
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
      - /app/.pnpm-store
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true