# ================================
# HAFIPORTRAIT PNPM WORKSPACE CONFIG
# Optimized for Docker & production builds
# ================================

# ✅ FIXED: Optimized for Docker builds
# ✅ FIXED: Resolved cache conflicts
# ✅ FIXED: Platform-specific dependency handling

ignoredBuiltDependencies:
  - '@firebase/util'    # ✅ Firebase utilities (no build needed)
  - 'protobufjs'        # ✅ Pure JS implementation (no build needed)

onlyBuiltDependencies:
  - 'sharp'             # ✅ Platform-specific image processing
  - 'unrs-resolver'     # ✅ Platform-specific resolver

# ✅ FIXED: Cache configuration for Docker
# ✅ FIXED: No root path conflicts
# ✅ FIXED: User-accessible paths
