version: 1

agent:
  # Additional system prompt untuk konsistensi dan efisiensi konteks
  additionalSystemPrompt: |
    Anda adalah "Rovo Dev" - AI assistant yang fokus pada efisiensi dan konsistensi.
    
    PRINSIP OPTIMASI KONTEKS:
    1. Selalu gunakan tool calls simultan untuk operasi independen
    2. Hindari membuka file yang sama berulang kali
    3. Fokus pada solusi yang tepat sasaran dan efisien
    4. Gunakan expand_code_chunks hanya jika diperlukan setelah open_files
    5. Prioritaskan testing yang relevan, bukan comprehensive testing
    
    KONSISTENSI BEHAVIOR:
    - Selalu akhiri dengan pertanyaan untuk langkah selanjutnya
    - Gunakan bahasa Indonesia jika user menggunakan bahasa Indonesia
    - Berikan status update natural sebelum setiap grup aksi
    - Fokus pada solusi general purpose, bukan hard-coded
    
    WORKSPACE CONTEXT:
    - Ini adalah HafiPortrait Photography system dengan Smart Storage
    - System sudah 100% complete dengan R2, Google Drive, Local storage
    - EventStorageManager untuk end-of-event backup sudah implemented
    - Mobile optimization dan real device testing framework sudah ready
  
  # Streaming untuk responsivitas yang lebih baik
  streaming: true
  
  # Temperature rendah untuk konsistensi output
  temperature: 0.1
  
  # Model yang optimal untuk development tasks
  modelId: claude-sonnet-4@20250514
  
  experimental:
    # Shadow mode disabled untuk efisiensi
    enableShadowMode: false

sessions:
  # Auto restore untuk kontinuitas konteks
  autoRestore: true
  
  # Persistence directory
  persistenceDir: /home/ubuntu/.rovodev/sessions
  
  # Optimasi session management
  maxSessionHistory: 50
  contextCompressionThreshold: 8000

console:
  # Markdown untuk readability yang lebih baik
  outputFormat: markdown
  
  # Hide tool results untuk mengurangi noise
  showToolResults: false
  
  # EMACS mode untuk editing yang efisien
  editingMode: EMACS
  
  # Width yang optimal untuk development
  maxOutputWidth: 120
  
  # Optimasi console output
  compactMode: true
  showTimestamps: false

logging:
  # Log path
  path: /home/ubuntu/.rovodev/rovodev.log
  
  # Log level untuk mengurangi noise
  level: INFO
  
  # Rotate logs untuk menghemat space
  maxSize: 10MB
  maxFiles: 3

mcp:
  # MCP config path
  mcpConfigPath: /home/ubuntu/.rovodev/mcp.json

toolPermissions:
  # Default permission yang lebih permissive untuk efisiensi
  default: allow
  
  # Tool permissions yang dioptimasi
  tools:
    # File operations - allow untuk efisiensi development
    create_file: allow
    delete_file: ask
    move_file: ask
    find_and_replace_code: allow
    
    # Read operations - semua allow
    open_files: allow
    expand_code_chunks: allow
    expand_folder: allow
    grep: allow
    grep_file_content: allow
    grep_file_paths: allow
    
    # Atlassian tools - allow untuk productivity
    getAccessibleAtlassianResources: allow
    getConfluenceSpaces: allow
    getConfluencePages: allow
    getPagesInConfluenceSpace: allow
    getConfluencePageAncestors: allow
    getConfluencePageFooterComments: allow
    getConfluencePageInlineComments: allow
    getConfluencePageDescendants: allow
    searchConfluenceUsingCql: allow
    getJiraIssue: allow
    getTransitionsForJiraIssue: allow
    lookupJiraAccountId: allow
    searchJiraIssuesUsingJql: allow
    getJiraIssueRemoteIssueLinks: allow
    getVisibleJiraProjects: allow
    getJiraProjectIssueTypesMetadata: allow
    
    # Write operations - ask untuk safety
    createConfluencePage: ask
    updateConfluencePage: ask
    createConfluenceFooterComment: ask
    createConfluenceInlineComment: ask
    editJiraIssue: ask
    createJiraIssue: ask
    transitionJiraIssue: ask
    addCommentToJiraIssue: ask
    
    # Technical planning - allow
    create_technical_plan: allow
    
  bash:
    # Default permission yang lebih permissive
    default: allow
    
    # Specific commands dengan permission yang dioptimasi
    commands:
    # Basic commands - allow
    - command: ls.*
      permission: allow
    - command: cat.*
      permission: allow
    - command: echo.*
      permission: allow
    - command: pwd
      permission: allow
    - command: grep.*
      permission: allow
    - command: find.*
      permission: allow
    - command: head.*
      permission: allow
    - command: tail.*
      permission: allow
    - command: wc.*
      permission: allow
    
    # Git commands - allow untuk development efficiency
    - command: git status
      permission: allow
    - command: git diff.*
      permission: allow
    - command: git log.*
      permission: allow
    - command: git branch.*
      permission: allow
    - command: git show.*
      permission: allow
    
    # Package management - allow
    - command: pnpm.*
      permission: allow
    - command: npm.*
      permission: allow
    - command: node.*
      permission: allow
    
    # TypeScript checking - allow untuk development
    - command: pnpm -w tsc --noEmit.*
      permission: allow
    
    # Testing commands - allow
    - command: pnpm test.*
      permission: allow
    - command: pnpm build.*
      permission: allow
    
    # System monitoring - allow
    - command: ps.*
      permission: allow
    - command: top.*
      permission: allow
    - command: htop.*
      permission: allow
    - command: df.*
      permission: allow
    - command: du.*
      permission: allow
    
    # File operations yang aman - allow
    - command: cp.*
      permission: allow
    - command: mv.*
      permission: ask
    - command: rm.*
      permission: ask
    - command: mkdir.*
      permission: allow
    - command: chmod.*
      permission: ask
    
    # Network commands - ask untuk safety
    - command: curl.*
      permission: ask
    - command: wget.*
      permission: ask
    - command: ssh.*
      permission: ask
    
  # MCP servers yang diizinkan
  allowedMcpServers: []
  
  # External paths yang diizinkan untuk akses workspace
  allowedExternalPaths: 
    - /home/ubuntu/.rovodev/
    - /tmp/
    - /var/tmp/

# Optimasi tambahan untuk performance
performance:
  # Cache settings untuk mengurangi redundant operations
  enableCache: true
  cacheTimeout: 300  # 5 minutes
  
  # Batch operations untuk efisiensi
  batchSize: 5
  maxConcurrentOperations: 3
  
  # Context management
  maxContextTokens: 100000
  contextCompressionRatio: 0.7
  
  # Response optimization
  streamingChunkSize: 1024
  responseTimeout: 30

# Workspace-specific optimizations untuk HafiPortrait
workspace:
  # Project type untuk context-aware behavior
  projectType: "nextjs-photography-system"
  
  # Key directories untuk fokus development
  keyDirectories:
    - "src/"
    - "DSLR-System/"
    - "scripts/"
    - "docs/"
  
  # File patterns yang sering diakses
  commonPatterns:
    - "*.ts"
    - "*.tsx" 
    - "*.js"
    - "*.jsx"
    - "*.md"
    - "*.yml"
    - "*.yaml"
    - "*.json"
  
  # Ignore patterns untuk mengurangi noise
  ignorePatterns:
    - "node_modules/"
    - ".next/"
    - "dist/"
    - "build/"
    - "*.log"
    - ".git/"