version: 1

agent:
  # System prompt yang ringkas tapi efektif
  additionalSystemPrompt: |
    Rovo Dev - AI assistant efisien untuk HafiPortrait Photography system.
    
    EFISIENSI TOKEN:
    - Gunakan tool calls simultan
    - Hindari repetisi file operations
    - Jawaban singkat tapi lengkap
    - Fokus pada solusi tepat sasaran
    
    BEHAVIOR:
    - Bahasa Indonesia jika user pakai Indonesia
    - Akhiri dengan pertanyaan next step
    - Status update singkat sebelum aksi
  
  streaming: true
  temperature: 0.2  # Sedikit lebih tinggi untuk variasi yang efisien
  modelId: claude-sonnet-4@20250514
  experimental:
    enableShadowMode: false

sessions:
  autoRestore: true
  persistenceDir: /home/ubuntu/.rovodev/sessions

console:
  outputFormat: markdown
  showToolResults: false  # Hemat token dengan hide tool results
  editingMode: EMACS
  maxOutputWidth: 100     # Lebih sempit untuk hemat token

logging:
  path: /home/ubuntu/.rovodev/rovodev.log

mcp:
  mcpConfigPath: /home/ubuntu/.rovodev/mcp.json

toolPermissions:
  default: allow  # Hemat token dengan less prompting
  
  tools:
    # Core operations - allow
    create_file: allow
    delete_file: ask
    move_file: ask
    find_and_replace_code: allow
    open_files: allow
    expand_code_chunks: allow
    grep: allow
    
    # Atlassian - allow yang penting saja
    getAccessibleAtlassianResources: allow
    getConfluenceSpaces: allow
    getJiraIssue: allow
    searchJiraIssuesUsingJql: allow
    getVisibleJiraProjects: allow
    
    # Write operations - ask
    createConfluencePage: ask
    editJiraIssue: ask
    createJiraIssue: ask
    
  bash:
    default: allow  # Hemat token dengan less asking
    
    # Commands penting saja
    commands:
    - command: ls.*
      permission: allow
    - command: cat.*
      permission: allow
    - command: echo.*
      permission: allow
    - command: git.*
      permission: allow
    - command: pnpm.*
      permission: allow
    - command: npm.*
      permission: allow
    - command: node.*
      permission: allow
    - command: grep.*
      permission: allow
    - command: find.*
      permission: allow
    - command: cp.*
      permission: allow
    - command: mv.*
      permission: ask
    - command: rm.*
      permission: ask
    
  allowedMcpServers: []
  allowedExternalPaths: 
    - /home/ubuntu/.rovodev/